name: ${project.name}
version: ${project.version}
description: Powerful chat API for Bukkit
depend: []
softdepend: [Vault]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.chatomizer.ChatomizerPlugin
commands:
  chatomizer:
    aliases: [chatomiser, cm, chatstyle, cstyle, chat]